# Generated by Django 3.2 on 2022-10-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_enquiry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='enquiry_type',
            field=models.CharField(choices=[('DESIGN_CONSULTATION', 'Design Consultation Enquiry'), ('PRODUCT_QUERY', 'Product Query'), ('ORDER_QUERY', 'Order Query'), ('OTHER', 'Other')], default='DS', max_length=254),
        ),
    ]
