# Generated by Django 3.2 on 2022-10-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_testimonial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousproject',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
