# Generated by Django 3.2 on 2022-09-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220905_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_dispatch',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
