# Generated by Django 3.2 on 2022-10-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='liked',
        ),
    ]
